Increment3
shurikeagle/metrics-collector pull request #5
Opened 2022-09-04 15:12 UTC by shurikeagle

2022-09-06 20:48 UTC, avhitrov requested changes
Гонки и незакрытые ресурсы.

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/metricsendler/metricsendler.go
> +	ticker := time.NewTicker(s.reportInterval)
Тикер необходимо останавливать, чтобы не терять ресурсы
https://gobyexample.com/tickers
https://pkg.go.dev/time#NewTicker

проще всего в этом месте и через defer

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/metricsendler/metricsendler.go
> +}
Вот так примерно http-серваки и кладут. Не надо переделывать, но почитать стоит.

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/metricsendler/metricsendler.go
> +	timeoutCtx, cancelFunc := context.WithTimeout(context.Background(), sendTimeout)
:thumbsup:

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/metric/metric.go
> +}
Скомпилируй сервер и агент с ключом --race и посмотри на гонки, которые появляются при работе с данной структурой.

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/pollworker/pollworker.go
> +	ticker := time.NewTicker(w.pollInterval)
Тикер необходимо останавливать в конце работы с ним

2022-09-06 20:48 UTC, avhitrov commented on internal/agent/pollworker/pollworker.go
> +	w.pollCounter = 0
:thumbsup:

2022-09-06 20:48 UTC, avhitrov commented on internal/server/storage/inmemory/inmemRepository.go
> +}
Вот эта структура тоже является источником гонок. Достаточно понимать, что каждый запрос к серверу на чтение или запись является отдельной горутиной.

2022-09-06 20:48 UTC, avhitrov commented on internal/server/metrichandler/update.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Немного overengineered. Функции хендлера можно сразу описывать, как
```suggestion
	func (h *handler) updateHandler (w http.ResponseWriter, r *http.Request) {
```
А в раутер их вставлять в виде объектов, а не в виде вызова функции, которая возвращает функцию.
```
h.Post("/update/{metricType}/{metricName}/{metricValue}", h.updateHandler)
```
Не блокер, скорее оптимизация, для повышения читабельности.

2022-09-07 19:39 UTC, shurikeagle commented on internal/agent/metricsendler/metricsendler.go
> +}
Не понял, в том плане, что не ограничил максимально кол-во параллельных запросов или еще какая-то проблема есть?

2022-09-07 19:42 UTC, shurikeagle commented on internal/server/storage/inmemory/inmemRepository.go
> +}
Подозревал, что будет замечание насчет гонок, но думал, что пока на курсе не было темы многопоточности, я "не знаю" про примитивы синхронизации и гонки в целом и трогать код в этом направлении не должен=)
Поправил, добавил RWMutex

2022-09-07 20:26 UTC, avhitrov requested changes
Тикер поправлен, гонки остались.

2022-09-07 20:26 UTC, avhitrov commented on internal/agent/metricsendler/metricsendler.go
> +}
Да, именно, одновременное количество параллельных запросов.

2022-09-07 20:26 UTC, avhitrov commented on internal/agent/pollworker/pollworker.go
> +	mx           sync.RWMutex
Гонки никуда не делись. Мьютекс не на месте - его нужно вешать на ту структуру, которая является источником проблем. И лочить не только чтение (RLock), но и запись в нее (Lock).

2022-09-07 20:26 UTC, avhitrov commented on internal/server/storage/inmemory/inmemRepository.go
> +}
Так сервер же падает. И авторы курса считают этот элемент (разобраться, почему падают) хорошей темой для самостоятельного изучения. В двух словах - любая переменная или структура, к которой организуется одновременный доступ на чтение и запись с нескольких источников должна защищаться мьютексом. Этот мьютекс должен оборачивать все операции доступа к переменной или структуре. Иначе получаем попытку прочитать данные из слайса, который изменен другим процессом. Паника и смерть приложения.

RWMutex хорош тем, что при одновременных запросах на чтение не блокирует структуру. Защищает только запись от чтения и чтение от записи.

В текущей версии защиты на запись не нашел. И гонки и падение сервера это подтверждают.

2022-09-16 23:54 UTC, shurikeagle commented on internal/agent/metricsendler/metricsendler.go
> +}
Решил таки поправить, возможно, мое решение слишком наивно и имеет подводные камни

2022-09-20 19:30 UTC, avhitrov approved these changes

2022-09-20 19:30 UTC, avhitrov commented on internal/agent/metricsendler/metricsendler.go
> +}
👍

2022-09-20 19:31 UTC, avhitrov commented
Можно мержить в мастер.

2022-09-20 20:46 UTC, merged